project:
  type: website

website:
  title: "Connair J. S. Russell"
  navbar:
    left:
      - text: About
        href: index.qmd
      - text: blog
        href: blog.qmd
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
        
bibliography: references.bib
csl: apa.csl


format:
  html:
    theme: lux
    css: styles.css



